### ISSUE TITLE
Dockerize project with 2 python files and a run.sh bash file

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/sanchay-ai#1]
I'm looking for help dockerising this project, which consists of 2 python files and a run.sh bash file. 

I'd appreciate some assistance in containerising the project. 

If you're experienced with Docker and interested in this task, please reach out by commenting on this issue.

**Comment by ssk090** [comment]
Hey @aadeshkulkarni, I have raised a PR for the same. Please check https://github.com/aadeshkulkarni/sanchay-ai/pull/2

**Comment by aadeshkulkarni** [comment]
Approved & Merged. Thanks for contributing :)
